<?php

namespace CoreBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class FilmRepository extends \Doctrine\ORM\EntityRepository
{

    public function noFilter($min, $max)
    {
        $qb = $this->createQueryBuilder('f');

        $qb->where('f.id >= :min')->setParameter('min', $min)->andWhere('f.id <= :max')->setParameter('max', $max);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function filter($filter)
    {
        $qb = $this->createQueryBuilder('o');

        if(array_key_exists('search', $filter))
        {
            $qb->where('o.title LIKE :word')
                ->setParameter('word', '%'.$filter['search'].'%');
        }
        else if (array_key_exists('years', $filter) && array_key_exists('rated', $filter))
        {
            $qb->where('o.year = :year')
                ->setParameter('year', $filter['years'])
                ->andWhere('o.rating >= :rated')
                ->setParameter('rated', $filter['rated']);
        }
        else if(!array_key_exists('years', $filter) && array_key_exists('rated', $filter))
        {
            $qb->Where('o.rating >= :rated')
                ->setParameter('rated', $filter['rated']);
        }
        else if(array_key_exists('years', $filter) && !array_key_exists('rated', $filter))
        {
            $qb->where('o.year = :year')
                ->setParameter('year', $filter['years']);
        }

        if(array_key_exists('filter', $filter))
        {
            if($filter['filter'] == 'year')
                $qb->orderBy('o.year', 'DESC');
            else if($filter['filter'] == 'title')
                $qb->orderBy('o.title', 'ASC');
        }

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function count()
    {
        return $this->createQueryBuilder('f')
            ->select('COUNT(f)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function latestFilm()
    {
        return  $this->createQueryBuilder('f')
            ->orderBy('f.datetime', 'DESC')
            ->setMaxResults(12)
            ->getQuery()
            ->getArrayResult();
    }

    public function mostView()
    {
        return  $this->createQueryBuilder('f')
            ->orderBy('f.view', 'DESC')
            ->setMaxResults(12)
            ->getQuery()
            ->getArrayResult();
    }

    public function findByIdmdb($id)
    {
        return $this->createQueryBuilder('f')
            ->where('f.idmdb = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
