<?php

namespace CoreBundle\Repository;

/**
 * OMDbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OMDbRepository extends \Doctrine\ORM\EntityRepository
{
}
