<?php

namespace CoreBundle\Repository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{
    public function latestSerie()
    {
        return  $this->createQueryBuilder('s')
            ->orderBy('s.datetime', 'DESC')
            ->setMaxResults(12)
            ->getQuery()
            ->getArrayResult();
    }

    public function mostView()
    {
        return  $this->createQueryBuilder('s')
            ->orderBy('s.view', 'DESC')
            ->setMaxResults(12)
            ->getQuery()
            ->getArrayResult();
    }
}
