<?php

namespace Proxies\__CG__\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Episode extends \CoreBundle\Entity\Episode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'id', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'seriename', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'episode', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'season', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'datetime', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'view', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'viewrating', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'viewratingnumber', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'streamlanguage', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'streamsource', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'streamquality', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'link', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'alreadysee'];
        }

        return ['__isInitialized__', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'id', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'seriename', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'episode', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'season', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'datetime', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'view', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'viewrating', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'viewratingnumber', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'streamlanguage', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'streamsource', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'streamquality', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'link', '' . "\0" . 'CoreBundle\\Entity\\Episode' . "\0" . 'alreadysee'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Episode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriename($seriename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriename', [$seriename]);

        return parent::setSeriename($seriename);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriename', []);

        return parent::getSeriename();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpisode($episode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpisode', [$episode]);

        return parent::setEpisode($episode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpisode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpisode', []);

        return parent::getEpisode();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeason($season)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeason', [$season]);

        return parent::setSeason($season);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeason', []);

        return parent::getSeason();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetime($datetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetime', [$datetime]);

        return parent::setDatetime($datetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetime', []);

        return parent::getDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setView($view)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setView', [$view]);

        return parent::setView($view);
    }

    /**
     * {@inheritDoc}
     */
    public function getView()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getView', []);

        return parent::getView();
    }

    /**
     * {@inheritDoc}
     */
    public function setViewrating($viewrating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViewrating', [$viewrating]);

        return parent::setViewrating($viewrating);
    }

    /**
     * {@inheritDoc}
     */
    public function getViewrating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewrating', []);

        return parent::getViewrating();
    }

    /**
     * {@inheritDoc}
     */
    public function setViewratingnumber($viewratingnumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViewratingnumber', [$viewratingnumber]);

        return parent::setViewratingnumber($viewratingnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getViewratingnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewratingnumber', []);

        return parent::getViewratingnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreamlanguage($streamlanguage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreamlanguage', [$streamlanguage]);

        return parent::setStreamlanguage($streamlanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreamlanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreamlanguage', []);

        return parent::getStreamlanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreamsource($streamsource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreamsource', [$streamsource]);

        return parent::setStreamsource($streamsource);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreamsource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreamsource', []);

        return parent::getStreamsource();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreamquality($streamquality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreamquality', [$streamquality]);

        return parent::setStreamquality($streamquality);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreamquality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreamquality', []);

        return parent::getStreamquality();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', [$link]);

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', []);

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlreadysee($alreadysee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlreadysee', [$alreadysee]);

        return parent::setAlreadysee($alreadysee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlreadysee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlreadysee', []);

        return parent::getAlreadysee();
    }

}
