<?php

namespace Proxies\__CG__\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Serie extends \CoreBundle\Entity\Serie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'id', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'datetime', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'view', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'title', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'year', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'released', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'runtime', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'genre', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'director', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'writer', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'actors', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'plot', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'poster', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'rating', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'rated', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'idmdb', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'language'];
        }

        return ['__isInitialized__', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'id', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'datetime', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'view', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'title', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'year', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'released', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'runtime', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'genre', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'director', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'writer', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'actors', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'plot', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'poster', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'rating', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'rated', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'idmdb', '' . "\0" . 'CoreBundle\\Entity\\Serie' . "\0" . 'language'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Serie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear($year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', [$year]);

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', []);

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setReleased($released)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReleased', [$released]);

        return parent::setReleased($released);
    }

    /**
     * {@inheritDoc}
     */
    public function getReleased()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReleased', []);

        return parent::getReleased();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuntime($runtime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuntime', [$runtime]);

        return parent::setRuntime($runtime);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuntime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuntime', []);

        return parent::getRuntime();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirector($director)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirector', [$director]);

        return parent::setDirector($director);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirector', []);

        return parent::getDirector();
    }

    /**
     * {@inheritDoc}
     */
    public function setWriter($writer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWriter', [$writer]);

        return parent::setWriter($writer);
    }

    /**
     * {@inheritDoc}
     */
    public function getWriter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWriter', []);

        return parent::getWriter();
    }

    /**
     * {@inheritDoc}
     */
    public function setActors($actors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActors', [$actors]);

        return parent::setActors($actors);
    }

    /**
     * {@inheritDoc}
     */
    public function getActors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActors', []);

        return parent::getActors();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlot($plot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlot', [$plot]);

        return parent::setPlot($plot);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlot', []);

        return parent::getPlot();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoster($poster)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoster', [$poster]);

        return parent::setPoster($poster);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoster()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoster', []);

        return parent::getPoster();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setRated($rated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRated', [$rated]);

        return parent::setRated($rated);
    }

    /**
     * {@inheritDoc}
     */
    public function getRated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRated', []);

        return parent::getRated();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmdb($idmdb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmdb', [$idmdb]);

        return parent::setIdmdb($idmdb);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmdb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmdb', []);

        return parent::getIdmdb();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetime($datetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetime', [$datetime]);

        return parent::setDatetime($datetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetime', []);

        return parent::getDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setView($view)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setView', [$view]);

        return parent::setView($view);
    }

    /**
     * {@inheritDoc}
     */
    public function getView()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getView', []);

        return parent::getView();
    }

}
